### ISSUE TITLE
Set Up Database Integration with EF Core

### ISSUE THREAD

**Issue by aafgani** [aafgani/aspire-project#40]
**Description:**
Add Entity Framework Core, configure the DbContext, and setup code-first model for ToDoList and TaskItem.

**Checklist:**
- Add EF Core NuGet packages
- Define ToDoList, TaskItem models
- Create ToDoDbContext
- Configure connection string from appsettings.json
- Add IServiceCollection registration
- Run dotnet ef migrations add Initial and apply migration

**Schema** : 
```
-- Create ToDoList table
CREATE TABLE ToDoLists (
    Id INT PRIMARY KEY IDENTITY(1,1),
    Title NVARCHAR(255) NOT NULL,
    Description NVARCHAR(MAX) NULL,
    CreatedAt DATETIME2 NOT NULL DEFAULT GETDATE(),
    UserId NVARCHAR(255) NOT NULL -- External user identity (e.g., Entra ID objectId)
);

-- Create Tasks table
CREATE TABLE Tasks (
    Id INT PRIMARY KEY IDENTITY(1,1),
    Title NVARCHAR(255) NOT NULL,
    Notes NVARCHAR(MAX) NULL,
    IsCompleted BIT NOT NULL DEFAULT 0,
    DueDate DATETIME2 NULL,
    CreatedAt DATETIME2 NOT NULL DEFAULT GETDATE(),
    ToDoListId INT NOT NULL,
    FOREIGN KEY (ToDoListId) REFERENCES ToDoLists(Id) ON DELETE CASCADE
);

-- Optional: Indexes
CREATE INDEX IX_Tasks_ToDoListId ON Tasks(ToDoListId);
CREATE INDEX IX_ToDoLists_UserId ON ToDoLists(UserId);

```

**Comment by aafgani** [comment]
docker compose set up

```
version: "3.9"

services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: tododb
    environment:
      SA_PASSWORD: "Your_strong_password123"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    volumes:
      - ./sql-scripts:/init
    command: >
      /bin/bash -c "
        /opt/mssql/bin/sqlservr &
        sleep 15 &&
        /opt/mssql-tools/bin/sqlcmd -S localhost -U sa -P Your_strong_password123 -d master -i /init/initial-schema.sql
      "

```
